notifications:
  email: false

language: go

install: true

env:
- GO111MODULE=on

before_script:
- make install-linter

matrix:
  include:
  - go: "1.10.x"
    script:
    - make lint-v110
    - make test
  - go: "1.11.x"
    env: GOFLAGS=-mod=vendor
    script:
    - make lint
    # fails without -a
    - go test -a ./... # make test
  - go: "1.12.x"
    env: GOFLAGS=-mod=vendor
    script:
    - make lint
    # fails without -a
    - go test -a ./... # make test
